name: Handle issues

on: issues

jobs:
 output-info:
  runs-on: ubuntu-latest
  steps:   
   - name: Output issue info
     run: |
       echo "Issue action: ${{ github.event.action }}"
       echo "Issue title: ${{ github.event.issue.title }}"
       echo "Issue body: ${{ github.event.issue.body }}"
       echo "Issue number: ${{ github.event.issue.number }}"
       echo "Issue URL: ${{ github.event.issue.html_url }}"
  
